#ifndef EPD_CUSTOM_MEM_MAP_H
#define EPD_CUSTOM_MEM_MAP_H

#ifdef USING_PARTITION_TABLE
#include "ptab.h"
#endif

#define FAL_PART_TABLE \
{ \
    {FAL_PART_MAGIC_WORD, "ble", NOR_FLASH2_DEV_NAME, KVDB_BLE_REGION_OFFSET, KVDB_BLE_REGION_SIZE, 0}, \
}

#endif
