Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

linkflags = []
if ARGUMENTS.get('TLS_CERT_DIAG') == '1':
    linkflags = ['-Wl,--wrap=' + name for name in (
        'mbedtls_x509_crt_parse', 'mbedtls_client_context',
        'mbedtls_md', 'mbedtls_pk_verify_ext')]
else:
    SrcRemove(src, 'tls_cert_diag.c')

group = DefineGroup('network', src, depend = [''], CPPPATH = CPPPATH,
                    LINKFLAGS = linkflags)

Return('group')
