import os
import rtconfig

# Check SDK 
SIFLI_SDK = os.getenv('SIFLI_SDK')
if not SIFLI_SDK:
    print("Please run set_env.bat in root folder of SIFLI SDK to set environment.")
    exit()
from building import *

# Prepare environment.
PrepareEnv()

################################## change rtconfig.xxx to customize build ########################################

# Add bootloader project
AddBootLoader(SIFLI_SDK,rtconfig.CHIP)

# Add LCPU project
AddLCPU(SIFLI_SDK,rtconfig.CHIP,"../../src/lcpu_img.c")
# Set default compile options
SifliEnv()

TARGET = rtconfig.OUTPUT_DIR + rtconfig.TARGET_NAME + '.' + rtconfig.TARGET_EXT
env = Environment(tools = ['mingw'],
    AS = rtconfig.AS, ASFLAGS = rtconfig.AFLAGS,
    CC = rtconfig.CC, CFLAGS = rtconfig.CFLAGS,
    CXX = rtconfig.CXX, CXXFLAGS = rtconfig.CXXFLAGS,
    AR = rtconfig.AR, ARFLAGS = '-rc',
    LINK = rtconfig.LINK, LINKFLAGS = rtconfig.LFLAGS)
env.PrependENVPath('PATH', rtconfig.EXEC_PATH)
   
# Prepare building environment
objs = PrepareBuilding(env)

# Build application.
DoBuilding(TARGET, objs)

# Configuration macros can change public structure layouts, so every compiled
# object must depend on rtconfig.h even when it is included through a macro.
config_header = env.File(os.path.join(rtconfig.OUTPUT_DIR, 'rtconfig.h'))
pending_nodes = list(env['target'])
visited_nodes = set()
while pending_nodes:
    node = pending_nodes.pop()
    if node in visited_nodes or not node.has_builder():
        continue
    visited_nodes.add(node)
    if os.path.splitext(str(node))[1] in ('.o', '.obj'):
        env.Depends(node, config_header)
    pending_nodes.extend(node.sources)

# Add flash table
AddFTAB(SIFLI_SDK,rtconfig.CHIP)


# Add existing file system image bin
fs_bin=FileSystemBuild( "../disk", env)
AddCustomImg("fs_root",bin=[fs_bin])


# Add EPD wave form image bin
if GetDepend('EPD_WAVEFORM_USE_BIN'):
    epd_wave_bin="../waveform/epd_waveform.bin"
    AddCustomImg("wave_table",bin=[epd_wave_bin])

# Generate download .bat script
GenDownloadScript(env)
