from building import *

cwd = GetCurrentDir()
objects = DefineGroup('hello', Glob('*.c'), depend=[''],
                      CPPPATH=[cwd], CPPDEFINES=['BUILD_DLMODULE', 'HAVE_CCONFIG_H'])
Return('objects')
