/* Generated by tools/generate_weather_icons.cjs. */
#include "weather_icons.h"

extern const lv_image_dsc_t w100_160;
extern const lv_image_dsc_t w100_48;
extern const lv_image_dsc_t w101_160;
extern const lv_image_dsc_t w101_48;
extern const lv_image_dsc_t w102_160;
extern const lv_image_dsc_t w102_48;
extern const lv_image_dsc_t w103_160;
extern const lv_image_dsc_t w103_48;
extern const lv_image_dsc_t w104_160;
extern const lv_image_dsc_t w104_48;
extern const lv_image_dsc_t w150_160;
extern const lv_image_dsc_t w150_48;
extern const lv_image_dsc_t w151_160;
extern const lv_image_dsc_t w151_48;
extern const lv_image_dsc_t w152_160;
extern const lv_image_dsc_t w152_48;
extern const lv_image_dsc_t w153_160;
extern const lv_image_dsc_t w153_48;
extern const lv_image_dsc_t w300_160;
extern const lv_image_dsc_t w300_48;
extern const lv_image_dsc_t w301_160;
extern const lv_image_dsc_t w301_48;
extern const lv_image_dsc_t w302_160;
extern const lv_image_dsc_t w302_48;
extern const lv_image_dsc_t w303_160;
extern const lv_image_dsc_t w303_48;
extern const lv_image_dsc_t w304_160;
extern const lv_image_dsc_t w304_48;
extern const lv_image_dsc_t w305_160;
extern const lv_image_dsc_t w305_48;
extern const lv_image_dsc_t w306_160;
extern const lv_image_dsc_t w306_48;
extern const lv_image_dsc_t w307_160;
extern const lv_image_dsc_t w307_48;
extern const lv_image_dsc_t w308_160;
extern const lv_image_dsc_t w308_48;
extern const lv_image_dsc_t w309_160;
extern const lv_image_dsc_t w309_48;
extern const lv_image_dsc_t w310_160;
extern const lv_image_dsc_t w310_48;
extern const lv_image_dsc_t w311_160;
extern const lv_image_dsc_t w311_48;
extern const lv_image_dsc_t w312_160;
extern const lv_image_dsc_t w312_48;
extern const lv_image_dsc_t w313_160;
extern const lv_image_dsc_t w313_48;
extern const lv_image_dsc_t w314_160;
extern const lv_image_dsc_t w314_48;
extern const lv_image_dsc_t w315_160;
extern const lv_image_dsc_t w315_48;
extern const lv_image_dsc_t w316_160;
extern const lv_image_dsc_t w316_48;
extern const lv_image_dsc_t w317_160;
extern const lv_image_dsc_t w317_48;
extern const lv_image_dsc_t w318_160;
extern const lv_image_dsc_t w318_48;
extern const lv_image_dsc_t w350_160;
extern const lv_image_dsc_t w350_48;
extern const lv_image_dsc_t w351_160;
extern const lv_image_dsc_t w351_48;
extern const lv_image_dsc_t w399_160;
extern const lv_image_dsc_t w399_48;
extern const lv_image_dsc_t w400_160;
extern const lv_image_dsc_t w400_48;
extern const lv_image_dsc_t w401_160;
extern const lv_image_dsc_t w401_48;
extern const lv_image_dsc_t w402_160;
extern const lv_image_dsc_t w402_48;
extern const lv_image_dsc_t w403_160;
extern const lv_image_dsc_t w403_48;
extern const lv_image_dsc_t w404_160;
extern const lv_image_dsc_t w404_48;
extern const lv_image_dsc_t w405_160;
extern const lv_image_dsc_t w405_48;
extern const lv_image_dsc_t w406_160;
extern const lv_image_dsc_t w406_48;
extern const lv_image_dsc_t w407_160;
extern const lv_image_dsc_t w407_48;
extern const lv_image_dsc_t w408_160;
extern const lv_image_dsc_t w408_48;
extern const lv_image_dsc_t w409_160;
extern const lv_image_dsc_t w409_48;
extern const lv_image_dsc_t w410_160;
extern const lv_image_dsc_t w410_48;
extern const lv_image_dsc_t w456_160;
extern const lv_image_dsc_t w456_48;
extern const lv_image_dsc_t w457_160;
extern const lv_image_dsc_t w457_48;
extern const lv_image_dsc_t w499_160;
extern const lv_image_dsc_t w499_48;
extern const lv_image_dsc_t w500_160;
extern const lv_image_dsc_t w500_48;
extern const lv_image_dsc_t w501_160;
extern const lv_image_dsc_t w501_48;
extern const lv_image_dsc_t w502_160;
extern const lv_image_dsc_t w502_48;
extern const lv_image_dsc_t w503_160;
extern const lv_image_dsc_t w503_48;
extern const lv_image_dsc_t w504_160;
extern const lv_image_dsc_t w504_48;
extern const lv_image_dsc_t w507_160;
extern const lv_image_dsc_t w507_48;
extern const lv_image_dsc_t w508_160;
extern const lv_image_dsc_t w508_48;
extern const lv_image_dsc_t w509_160;
extern const lv_image_dsc_t w509_48;
extern const lv_image_dsc_t w510_160;
extern const lv_image_dsc_t w510_48;
extern const lv_image_dsc_t w511_160;
extern const lv_image_dsc_t w511_48;
extern const lv_image_dsc_t w512_160;
extern const lv_image_dsc_t w512_48;
extern const lv_image_dsc_t w513_160;
extern const lv_image_dsc_t w513_48;
extern const lv_image_dsc_t w514_160;
extern const lv_image_dsc_t w514_48;
extern const lv_image_dsc_t w515_160;
extern const lv_image_dsc_t w515_48;
extern const lv_image_dsc_t w800_160;
extern const lv_image_dsc_t w800_48;
extern const lv_image_dsc_t w801_160;
extern const lv_image_dsc_t w801_48;
extern const lv_image_dsc_t w802_160;
extern const lv_image_dsc_t w802_48;
extern const lv_image_dsc_t w803_160;
extern const lv_image_dsc_t w803_48;
extern const lv_image_dsc_t w804_160;
extern const lv_image_dsc_t w804_48;
extern const lv_image_dsc_t w805_160;
extern const lv_image_dsc_t w805_48;
extern const lv_image_dsc_t w806_160;
extern const lv_image_dsc_t w806_48;
extern const lv_image_dsc_t w807_160;
extern const lv_image_dsc_t w807_48;
extern const lv_image_dsc_t w900_160;
extern const lv_image_dsc_t w900_48;
extern const lv_image_dsc_t w901_160;
extern const lv_image_dsc_t w901_48;
extern const lv_image_dsc_t w999_160;
extern const lv_image_dsc_t w999_48;

typedef struct { int code; const lv_image_dsc_t *large, *small; } weather_icon_entry_t;
static const weather_icon_entry_t entries[] = {
    {100, &w100_160, &w100_48},
    {101, &w101_160, &w101_48},
    {102, &w102_160, &w102_48},
    {103, &w103_160, &w103_48},
    {104, &w104_160, &w104_48},
    {150, &w150_160, &w150_48},
    {151, &w151_160, &w151_48},
    {152, &w152_160, &w152_48},
    {153, &w153_160, &w153_48},
    {300, &w300_160, &w300_48},
    {301, &w301_160, &w301_48},
    {302, &w302_160, &w302_48},
    {303, &w303_160, &w303_48},
    {304, &w304_160, &w304_48},
    {305, &w305_160, &w305_48},
    {306, &w306_160, &w306_48},
    {307, &w307_160, &w307_48},
    {308, &w308_160, &w308_48},
    {309, &w309_160, &w309_48},
    {310, &w310_160, &w310_48},
    {311, &w311_160, &w311_48},
    {312, &w312_160, &w312_48},
    {313, &w313_160, &w313_48},
    {314, &w314_160, &w314_48},
    {315, &w315_160, &w315_48},
    {316, &w316_160, &w316_48},
    {317, &w317_160, &w317_48},
    {318, &w318_160, &w318_48},
    {350, &w350_160, &w350_48},
    {351, &w351_160, &w351_48},
    {399, &w399_160, &w399_48},
    {400, &w400_160, &w400_48},
    {401, &w401_160, &w401_48},
    {402, &w402_160, &w402_48},
    {403, &w403_160, &w403_48},
    {404, &w404_160, &w404_48},
    {405, &w405_160, &w405_48},
    {406, &w406_160, &w406_48},
    {407, &w407_160, &w407_48},
    {408, &w408_160, &w408_48},
    {409, &w409_160, &w409_48},
    {410, &w410_160, &w410_48},
    {456, &w456_160, &w456_48},
    {457, &w457_160, &w457_48},
    {499, &w499_160, &w499_48},
    {500, &w500_160, &w500_48},
    {501, &w501_160, &w501_48},
    {502, &w502_160, &w502_48},
    {503, &w503_160, &w503_48},
    {504, &w504_160, &w504_48},
    {507, &w507_160, &w507_48},
    {508, &w508_160, &w508_48},
    {509, &w509_160, &w509_48},
    {510, &w510_160, &w510_48},
    {511, &w511_160, &w511_48},
    {512, &w512_160, &w512_48},
    {513, &w513_160, &w513_48},
    {514, &w514_160, &w514_48},
    {515, &w515_160, &w515_48},
    {800, &w800_160, &w800_48},
    {801, &w801_160, &w801_48},
    {802, &w802_160, &w802_48},
    {803, &w803_160, &w803_48},
    {804, &w804_160, &w804_48},
    {805, &w805_160, &w805_48},
    {806, &w806_160, &w806_48},
    {807, &w807_160, &w807_48},
    {900, &w900_160, &w900_48},
    {901, &w901_160, &w901_48},
    {999, &w999_160, &w999_48},
};

const lv_image_dsc_t *ui_weather_icon(int code, bool large)
{
    unsigned lo = 0, hi = sizeof(entries) / sizeof(entries[0]);
    while (lo < hi)
    {
        unsigned mid = lo + (hi - lo) / 2;
        if (entries[mid].code == code) return large ? entries[mid].large : entries[mid].small;
        if (entries[mid].code < code) lo = mid + 1;
        else hi = mid;
    }
    return large ? &w999_160 : &w999_48;
}
