/* Prepare grayscale weather PNGs and the LVGL lookup table for EZIP resources. */
const fs = require('node:fs');
const path = require('node:path');
const sharp = require('sharp');
const root = path.resolve(__dirname, '..');
const sourceDir = path.join(root, 'assets/weather');
const outDir = path.join(root, 'src/ui/icons');
const pngDir = path.join(root, 'assets/ezip/weather');
const sizes = [160, 48];
const FOREGROUND_GRAY = 0x11;

async function main() {
    fs.mkdirSync(pngDir, {recursive: true});
    const files = fs.readdirSync(sourceDir).filter(name => /^w\d+\.png$/.test(name))
        .sort((a, b) => Number(a.slice(1, -4)) - Number(b.slice(1, -4)));
    if (!files.includes('w999.png')) throw new Error('Unknown-weather icon w999 is required');
    const codes = files.map(name => Number(name.slice(1, -4)));
    if (new Set(codes).size !== codes.length) throw new Error('Duplicate weather code');
    let source = '/* Generated by tools/generate_weather_icons.cjs. */\n' +
        '#include "weather_icons.h"\n\n';
    for (const file of files) {
        const code = Number(file.slice(1, -4));
        for (const size of sizes) {
            const {data, info} = await sharp(path.join(sourceDir, file))
                .resize(size, size, {fit: 'contain', background: {r: 255, g: 255, b: 255, alpha: 0}})
                .toColourspace('srgb').ensureAlpha().raw().toBuffer({resolveWithObject: true});
            if (info.channels !== 4) throw new Error(`Unexpected format: ${file}`);
            for (let i = 0; i < size * size; ++i) {
                /* Preserve shape coverage; light source colors must not fade the foreground. */
                const alpha = Math.round(data[i * 4 + 3] / 17) * 17;
                data[i * 4] = data[i * 4 + 1] = data[i * 4 + 2] = FOREGROUND_GRAY;
                data[i * 4 + 3] = alpha;
            }
            const name = `w${code}_${size}`;
            await sharp(data, {raw: {width: size, height: size, channels: 4}})
                .png().toFile(path.join(pngDir, `${name}.png`));
            source += `extern const lv_image_dsc_t ${name};\n`;
        }
    }
    source += '\ntypedef struct { int code; const lv_image_dsc_t *large, *small; } weather_icon_entry_t;\n' +
        'static const weather_icon_entry_t entries[] = {\n';
    for (const code of codes) source += `    {${code}, &w${code}_160, &w${code}_48},\n`;
    source += '};\n\nconst lv_image_dsc_t *ui_weather_icon(int code, bool large)\n{\n' +
        '    unsigned lo = 0, hi = sizeof(entries) / sizeof(entries[0]);\n' +
        '    while (lo < hi)\n    {\n        unsigned mid = lo + (hi - lo) / 2;\n' +
        '        if (entries[mid].code == code) return large ? entries[mid].large : entries[mid].small;\n' +
        '        if (entries[mid].code < code) lo = mid + 1;\n        else hi = mid;\n    }\n' +
        '    return large ? &w999_160 : &w999_48;\n}\n';
    const header = '#ifndef WEATHER_ICONS_H\n#define WEATHER_ICONS_H\n#include "lvgl.h"\n#include <stdbool.h>\n\n' +
        `#define UI_WEATHER_ICON_COUNT ${files.length}\n` +
        '/* QWeather code lookup; large selects 160 px, otherwise 48 px. Unknown codes use 999. */\n' +
        'const lv_image_dsc_t *ui_weather_icon(int code, bool large);\n#endif\n';
    fs.mkdirSync(outDir, {recursive: true});
    fs.writeFileSync(path.join(outDir, 'weather_icons.c'), source);
    fs.writeFileSync(path.join(outDir, 'weather_icons.h'), header);
    console.log(`Prepared all ${files.length} weather icons at ${sizes.join('/')} px for EZIP`);
}
main().catch(error => {console.error(error); process.exitCode = 1;});
