/* Convert the complete weather PNG set into fixed-size, 16-gray LVGL A8 masks. */
const fs = require('node:fs');
const path = require('node:path');
const sharp = require('sharp');
const root = path.resolve(__dirname, '..');
const sourceDir = path.join(root, 'assets/weather');
const outDir = path.join(root, 'src/ui/icons');
const sizes = [160, 48];

async function main() {
    const files = fs.readdirSync(sourceDir).filter(name => /^w\d+\.png$/.test(name))
        .sort((a, b) => Number(a.slice(1, -4)) - Number(b.slice(1, -4)));
    if (!files.includes('w999.png')) throw new Error('Unknown-weather icon w999 is required');
    const codes = files.map(name => Number(name.slice(1, -4)));
    if (new Set(codes).size !== codes.length) throw new Error('Duplicate weather code');
    let source = '/* Generated by tools/generate_weather_icons.cjs. */\n' +
        '#include "weather_icons.h"\n\n' +
        '#if defined(__GNUC__)\n' +
        '#define WEATHER_ASSET __attribute__((section(".weather_assets"), aligned(32)))\n' +
        '#else\n#define WEATHER_ASSET LV_ATTRIBUTE_MEM_ALIGN\n#endif\n';
    for (const file of files) {
        const code = Number(file.slice(1, -4));
        for (const size of sizes) {
            const {data, info} = await sharp(path.join(sourceDir, file))
                .resize(size, size, {fit: 'contain', background: {r: 255, g: 255, b: 255, alpha: 0}})
                .toColourspace('srgb').ensureAlpha().raw().toBuffer({resolveWithObject: true});
            if (info.channels !== 4) throw new Error(`Unexpected format: ${file}`);
            const alpha = Array.from({length: size * size}, (_, i) => {
                const gray = (299 * data[i * 4] + 587 * data[i * 4 + 1] + 114 * data[i * 4 + 2]) / 1000;
                return Math.round(((255 - gray) * data[i * 4 + 3] / 255) / 17) * 17;
            });
            const name = `w${code}_${size}`;
            source += `\nstatic const uint8_t ${name}_data[] WEATHER_ASSET = {\n`;
            for (let i = 0; i < alpha.length; i += 32)
                source += '    ' + alpha.slice(i, i + 32).join(',') + ',\n';
            source += `};\nstatic const lv_image_dsc_t ${name} WEATHER_ASSET = {\n` +
                `    .header = {.magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_A8, .w = ${size}, .h = ${size}, .stride = ${size}},\n` +
                `    .data_size = sizeof(${name}_data), .data = ${name}_data,\n};\n`;
        }
    }
    source += '\ntypedef struct { int code; const lv_image_dsc_t *large, *small; } weather_icon_entry_t;\n' +
        'static const weather_icon_entry_t entries[] WEATHER_ASSET = {\n';
    for (const code of codes) source += `    {${code}, &w${code}_160, &w${code}_48},\n`;
    source += '};\n\nconst lv_image_dsc_t *ui_weather_icon(int code, bool large)\n{\n' +
        '    unsigned lo = 0, hi = sizeof(entries) / sizeof(entries[0]);\n' +
        '    while (lo < hi)\n    {\n        unsigned mid = lo + (hi - lo) / 2;\n' +
        '        if (entries[mid].code == code) return large ? entries[mid].large : entries[mid].small;\n' +
        '        if (entries[mid].code < code) lo = mid + 1;\n        else hi = mid;\n    }\n' +
        '    return large ? &w999_160 : &w999_48;\n}\n';
    const header = '#ifndef WEATHER_ICONS_H\n#define WEATHER_ICONS_H\n#include "lvgl.h"\n#include <stdbool.h>\n\n' +
        `#define UI_WEATHER_ICON_COUNT ${files.length}\n` +
        '/* QWeather code lookup; large selects 160 px, otherwise 48 px. Unknown codes use 999. */\n' +
        'const lv_image_dsc_t *ui_weather_icon(int code, bool large);\n#endif\n';
    fs.mkdirSync(outDir, {recursive: true});
    fs.writeFileSync(path.join(outDir, 'weather_icons.c'), source);
    fs.writeFileSync(path.join(outDir, 'weather_icons.h'), header);
    console.log(`Generated all ${files.length} weather icons at ${sizes.join('/')} px (${files.length * sizes.reduce((n, s) => n + s * s, 0)} pixel bytes)`);
}
main().catch(error => {console.error(error); process.exitCode = 1;});
