/* Convert the checked-in SVG artwork to antialiased LVGL v9 alpha masks. */
const fs = require('node:fs');
const path = require('node:path');
const sharp = require('sharp');
const root = path.resolve(__dirname, '..');
const icons = [
    ['bookshelf', '书架.svg', 80], ['weather', '天气.svg', 80],
    ['transfer', '文件传输.svg', 80], ['settings', '设置.svg', 80],
    ['album', '相册.svg', 80], ['wifi_entry', 'wifi状态-已连接.svg', 80],
    ['quick', '快捷信息.svg', 32], ['wifi_on', 'wifi状态-已连接.svg', 32],
    ['wifi_disconnected', 'wifi状态-未连接.svg', 32],
    ['bt_on', '蓝牙_bluetooth.svg', 32], ['bt_disconnected', '蓝牙状态-未连接.svg', 32],
    ['battery_empty', '电池没电_0-20.svg', 40],
    ['battery_mid', '电池运行_20-80.svg', 40],
    ['battery_full', '电池满电_80-100.svg', 40],
    ['battery_charge', '电池充电_battery-charge.svg', 40],
    ['key1', '按键一_one-key.svg', 28], ['key2', '按键二_two-key.svg', 28],
    ['key3', '按键三_three-key.svg', 28],
    ['location', '位置.svg', 32], ['humidity', '湿度.svg', 32],
    ['wind', '风速.svg', 32], ['sunrise', '日出_sunrise.svg', 32],
    ['sunset', '日落.svg', 32], ['pressure', '气压.svg', 32],
    ['air', '空气质量.svg', 32],
];
async function main() {
    let header = '#ifndef UI_ICONS_H\n#define UI_ICONS_H\n#include "lvgl.h"\n';
    let source = '/* Generated by tools/generate_ui_icons.cjs. */\n#include "ui_icons.h"\n';
    for (const [name, file, size] of icons) {
        const {data, info} = await sharp(path.join(root, 'assets/icons', file), {density: 384})
            .resize(size, size).ensureAlpha().raw().toBuffer({resolveWithObject: true});
        if (info.channels !== 4) throw new Error(`Unexpected channels: ${file}`);
        const alpha = Array.from({length: size * size}, (_, i) => Math.round(data[i * 4 + 3] / 17) * 17);
        source += `\nstatic const LV_ATTRIBUTE_MEM_ALIGN uint8_t ${name}_data[] = {\n`;
        for (let i = 0; i < alpha.length; i += 24)
            source += '    ' + alpha.slice(i, i + 24).map(v => '0x' + v.toString(16).padStart(2, '0')).join(', ') + ',\n';
        source += `};\nconst lv_image_dsc_t ui_icon_${name} = {\n` +
            `    .header = {.magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_A8, .w = ${size}, .h = ${size}, .stride = ${size}},\n` +
            `    .data_size = sizeof(${name}_data), .data = ${name}_data,\n};\n`;
        header += `extern const lv_image_dsc_t ui_icon_${name};\n`;
    }
    const out = path.join(root, 'src/ui/icons');
    fs.mkdirSync(out, {recursive: true});
    fs.writeFileSync(path.join(out, 'ui_icons.c'), source);
    fs.writeFileSync(path.join(out, 'ui_icons.h'), header + '#endif\n');
    console.log(`Generated ${icons.length} alpha-mask icons`);
}
main().catch(e => {console.error(e); process.exitCode = 1;});
