# for module compiling
import os
from building import *
import rtconfig

cwd = GetCurrentDir()

if GetDepend('EPD_USE_LVGL'):
    # LVGL UI 版本（当前唯一维护目标）
    src = ['main.c', 'pan.c', 'wheather.c']
else:
    # 自研渲染器版本已移除，保留空列表以备将来扩展
    src = []

CPPPATH = [cwd]

objs = DefineGroup('src', src, depend = [''], CPPPATH = CPPPATH)



list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

objs = objs + SConscript(os.path.join(cwd, '../waveform/SConscript'))

Return('objs')
