# for module compiling
import os
from building import *
import rtconfig

cwd = GetCurrentDir()

src = ['main.c']

CPPPATH = [cwd]

objs = DefineGroup('src', src, depend = [''], CPPPATH = CPPPATH)



list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

# 波形资源已随屏驱迁至 SDK（customer/peripherals/display/epd_e0470a03/waveform），
# 头/库由该目录 SConscript 提供，bin 由 SConstruct 打进 wave_table 分区。

Return('objs')
