from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
linkflags = []
if ARGUMENTS.get('HANG_DIAG') == '1':
    linkflags = ['-Wl,--wrap=' + name for name in (
        'lv_draw_epic_label', 'lv_draw_epic_img', 'drv_gpu_check_done')]
else:
    SrcRemove(src, 'hang_diag.c')
group = DefineGroup('platform_memory', src, depend=['EPD_USE_LVGL'],
                    CPPPATH=[cwd], LINKFLAGS=linkflags)
Return('group')
